[package]
name = "abundant-sums"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amicable-numbers = { path = "../21-amicable-numbers" }
